No configuration file found.
No pyproject.toml file found.
stubPath /mnt/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/typings is not a valid directory.
Assuming Python platform Linux
Searching for source files
Found 6 source files
/home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/main.py
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/main.py:10:8 - error: Import "mesh_tensorflow" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/main.py:11:8 - error: Import "tensorflow.compat.v1" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/main.py:12:6 - error: Import "tensorflow.python.tpu" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/main.py:13:6 - error: Import "tensorflow_estimator.python.estimator" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/main.py:14:6 - error: Import "utils" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/main.py:15:6 - error: Import "inputs" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/main.py:16:6 - error: Import "model_fns" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/main.py:17:6 - error: Import "encoders" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/main.py:18:6 - error: Import "configs" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/main.py:19:6 - error: Import "tokenizers" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/main.py:21:6 - error: Import "tasks" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/main.py:81:15 - error: "txt" is possibly unbound (reportUnboundVariable)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/main.py:81:37 - error: "txt" is possibly unbound (reportUnboundVariable)
/home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/model_fns.py
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/model_fns.py:1:8 - error: Import "mesh_tensorflow" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/model_fns.py:2:8 - error: Import "tensorflow.compat.v1" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/model_fns.py:3:6 - error: Import "tensorflow.python.tpu" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/model_fns.py:4:8 - error: Import "mesh_tensorflow.auto_mtf" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/model_fns.py:5:8 - error: Import "mesh_tensorflow.transformer" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/model_fns.py:8:6 - error: Import "optimizers" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/model_fns.py:9:6 - error: Import "utils" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/model_fns.py:10:6 - error: Import "models.utils" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/model_fns.py:12:6 - error: Import "sample" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/model_fns.py:13:6 - error: Import "models.gpt2" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/model_fns.py:33:39 - error: Cannot access member "num_hosts" for type "None"
    Member "num_hosts" is unknown (reportGeneralTypeIssues)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/model_fns.py:34:47 - error: Cannot access member "tpu_host_placement_function" for type "None"
    Member "tpu_host_placement_function" is unknown (reportGeneralTypeIssues)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/model_fns.py:42:62 - error: Cannot access member "num_replicas" for type "None"
    Member "num_replicas" is unknown (reportGeneralTypeIssues)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/model_fns.py:47:71 - error: Cannot access member "device_assignment" for type "None"
    Member "device_assignment" is unknown (reportGeneralTypeIssues)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/model_fns.py:75:9 - error: Argument of type "Literal['predict']" cannot be assigned to parameter "v" of type "None" in function "__setitem__"
    Type cannot be assigned to type "None" (reportGeneralTypeIssues)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/model_fns.py:78:9 - error: Argument of type "Literal['eval']" cannot be assigned to parameter "v" of type "None" in function "__setitem__"
    Type cannot be assigned to type "None" (reportGeneralTypeIssues)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/model_fns.py:81:9 - error: Argument of type "Literal['train']" cannot be assigned to parameter "v" of type "None" in function "__setitem__"
    Type cannot be assigned to type "None" (reportGeneralTypeIssues)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/model_fns.py:125:13 - error: Argument of type "Literal[False]" cannot be assigned to parameter "v" of type "None" in function "__setitem__"
    Type cannot be assigned to type "None" (reportGeneralTypeIssues)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/model_fns.py:129:37 - error: "mtf_samples" is possibly unbound (reportUnboundVariable)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/model_fns.py:165:5 - error: Argument of type "int" cannot be assigned to parameter "v" of type "None" in function "__setitem__"
    Type cannot be assigned to type "None" (reportGeneralTypeIssues)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/model_fns.py:215:122 - error: "var_grads" is possibly unbound (reportUnboundVariable)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/model_fns.py:238:67 - error: "update_ops" is possibly unbound (reportUnboundVariable)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/model_fns.py:238:67 - error: "Unbound" is not iterable (reportGeneralTypeIssues)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/model_fns.py:243:55 - error: "fully_replicated_mean_logits" is possibly unbound (reportUnboundVariable)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/model_fns.py:244:54 - error: "fully_replicated_max_logits" is possibly unbound (reportUnboundVariable)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/model_fns.py:245:66 - error: "fully_replicated_loss_batch" is possibly unbound (reportUnboundVariable)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/model_fns.py:270:26 - error: "train_op" is possibly unbound (reportUnboundVariable)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/model_fns.py:288:38 - error: Operator ">=" not supported for "None" (reportOptionalOperand)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/model_fns.py:303:62 - error: "tf_max_logits" is possibly unbound (reportUnboundVariable)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/model_fns.py:303:77 - error: "tf_loss_batch" is possibly unbound (reportUnboundVariable)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/model_fns.py:305:46 - error: "tf_mean_logits" is possibly unbound (reportUnboundVariable)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/model_fns.py:305:62 - error: "tf_loss_batch" is possibly unbound (reportUnboundVariable)
/home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/optimizers.py
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/optimizers.py:6:8 - error: Import "mesh_tensorflow" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/optimizers.py:7:8 - error: Import "tensorflow.compat.v1" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/optimizers.py:20:31 - error: "mesh" is not defined (reportUndefinedVariable)
/home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/sample.py
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/sample.py:1:8 - error: Import "mesh_tensorflow" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/sample.py:2:8 - error: Import "tensorflow.compat.v1" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/sample.py:3:8 - error: Import "mesh_tensorflow.transformer" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/sample.py:101:10 - error: Import "models.gpt2" could not be resolved (reportMissingImports)
/home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/test_models.py
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/test_models.py:1:8 - error: Import "pytest" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/test_models.py:9:8 - error: Import "mesh_tensorflow" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/test_models.py:10:6 - error: Import "mesh_tensorflow" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/test_models.py:12:6 - error: Import "models.gpt2" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/test_models.py:13:6 - error: Import "models.utils" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/test_models.py:74:56 - error: Operator "+" not supported for types "int | float | list[str] | tuple[Literal[32], Literal[32]] | str | tuple[Literal[1]] | bool | dict[str, float] | None" and "int | float | list[str] | tuple[Literal[32], Literal[32]] | str | tuple[Literal[1]] | bool | dict[str, float] | None"
    Operator "+" not supported for types "None" and "None"
    Operator "+" not supported for types "None" and "int"
    Operator "+" not supported for types "None" and "float"
    Operator "+" not supported for types "None" and "list[str]"
    Operator "+" not supported for types "None" and "tuple[Literal[32], Literal[32]]"
    Operator "+" not supported for types "None" and "str"
    Operator "+" not supported for types "None" and "tuple[Literal[1]]"
    Operator "+" not supported for types "None" and "bool"
    ... (reportGeneralTypeIssues)
/home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/models/gpt2/gpt2.py
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/models/gpt2/gpt2.py:2:8 - error: Import "mesh_tensorflow" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/models/gpt2/gpt2.py:3:8 - error: Import "tensorflow.compat.v1" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/models/gpt2/gpt2.py:5:8 - error: Import "mesh_tensorflow.transformer" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/models/gpt2/gpt2.py:6:6 - error: Import "utils" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/models/gpt2/gpt2.py:7:6 - error: Import "models.utils" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/EleutherAI_gpt-neo/0888dbfadee6eb1169a185a8ede3882ac42d1a72/a/models/gpt2/gpt2.py:271:13 - error: Argument missing for parameter "variable_dtype" (reportGeneralTypeIssues)
64 errors, 0 warnings, 0 infos 
Completed in 2.244sec

time cost(in seconds): 2.4362306594848633
