No configuration file found.
No pyproject.toml file found.
stubPath /mnt/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/keras-team_autokeras/b41a27ff173254642f634bb5e881fb8e7d863b00/typings is not a valid directory.
Assuming Python platform Linux
Searching for source files
Found 3 source files
/home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/keras-team_autokeras/b41a27ff173254642f634bb5e881fb8e7d863b00/a/autokeras/pretrained.py
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/keras-team_autokeras/b41a27ff173254642f634bb5e881fb8e7d863b00/a/autokeras/pretrained.py:2:6 - error: Import "autokeras.constant" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/keras-team_autokeras/b41a27ff173254642f634bb5e881fb8e7d863b00/a/autokeras/pretrained.py:3:6 - error: Import "autokeras.image.face_detection_pretrained" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/keras-team_autokeras/b41a27ff173254642f634bb5e881fb8e7d863b00/a/autokeras/pretrained.py:4:6 - error: Import "autokeras.utils" could not be resolved (reportMissingImports)
/home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/keras-team_autokeras/b41a27ff173254642f634bb5e881fb8e7d863b00/a/autokeras/image/face_detection_pretrained.py
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/keras-team_autokeras/b41a27ff173254642f634bb5e881fb8e7d863b00/a/autokeras/image/face_detection_pretrained.py:3:8 - error: Import "cv2" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/keras-team_autokeras/b41a27ff173254642f634bb5e881fb8e7d863b00/a/autokeras/image/face_detection_pretrained.py:4:8 - error: Import "torch" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/keras-team_autokeras/b41a27ff173254642f634bb5e881fb8e7d863b00/a/autokeras/image/face_detection_pretrained.py:5:8 - error: Import "torch.nn" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/keras-team_autokeras/b41a27ff173254642f634bb5e881fb8e7d863b00/a/autokeras/image/face_detection_pretrained.py:6:8 - error: Import "torchvision.transforms" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/keras-team_autokeras/b41a27ff173254642f634bb5e881fb8e7d863b00/a/autokeras/image/face_detection_pretrained.py:8:6 - error: Import "torch.autograd.variable" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/keras-team_autokeras/b41a27ff173254642f634bb5e881fb8e7d863b00/a/autokeras/image/face_detection_pretrained.py:10:8 - error: Import "matplotlib.pyplot" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/keras-team_autokeras/b41a27ff173254642f634bb5e881fb8e7d863b00/a/autokeras/image/face_detection_pretrained.py:11:8 - error: Import "matplotlib.patches" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/keras-team_autokeras/b41a27ff173254642f634bb5e881fb8e7d863b00/a/autokeras/image/face_detection_pretrained.py:240:35 - error: "use_cuda" is not a known member of "None" (reportOptionalMemberAccess)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/keras-team_autokeras/b41a27ff173254642f634bb5e881fb8e7d863b00/a/autokeras/image/face_detection_pretrained.py:243:28 - error: Object of type "None" cannot be called (reportOptionalCall)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/keras-team_autokeras/b41a27ff173254642f634bb5e881fb8e7d863b00/a/autokeras/image/face_detection_pretrained.py:316:31 - error: "use_cuda" is not a known member of "None" (reportOptionalMemberAccess)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/keras-team_autokeras/b41a27ff173254642f634bb5e881fb8e7d863b00/a/autokeras/image/face_detection_pretrained.py:319:24 - error: Object of type "None" cannot be called (reportOptionalCall)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/keras-team_autokeras/b41a27ff173254642f634bb5e881fb8e7d863b00/a/autokeras/image/face_detection_pretrained.py:390:31 - error: "use_cuda" is not a known member of "None" (reportOptionalMemberAccess)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/keras-team_autokeras/b41a27ff173254642f634bb5e881fb8e7d863b00/a/autokeras/image/face_detection_pretrained.py:393:34 - error: Object of type "None" cannot be called (reportOptionalCall)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/keras-team_autokeras/b41a27ff173254642f634bb5e881fb8e7d863b00/a/autokeras/image/face_detection_pretrained.py:549:25 - error: "ovr" is possibly unbound (reportUnboundVariable)
/home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/keras-team_autokeras/b41a27ff173254642f634bb5e881fb8e7d863b00/a/tests/test_pretrained.py
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/keras-team_autokeras/b41a27ff173254642f634bb5e881fb8e7d863b00/a/tests/test_pretrained.py:1:6 - error: Import "autokeras.pretrained" could not be resolved (reportMissingImports)
18 errors, 0 warnings, 0 infos 
Completed in 1.559sec

time cost(in seconds): 1.7313175201416016
