No configuration file found.
No pyproject.toml file found.
stubPath /mnt/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/IntelLabs_nlp-architect/3f63387cff88f0074f1946bbbd1163fbfe97073e/typings is not a valid directory.
Assuming Python platform Linux
Searching for source files
Found 1 source file
/home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/IntelLabs_nlp-architect/3f63387cff88f0074f1946bbbd1163fbfe97073e/a/solutions/set_expansion/prepare_data.py
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/IntelLabs_nlp-architect/3f63387cff88f0074f1946bbbd1163fbfe97073e/a/solutions/set_expansion/prepare_data.py:26:6 - error: Import "configargparse" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/IntelLabs_nlp-architect/3f63387cff88f0074f1946bbbd1163fbfe97073e/a/solutions/set_expansion/prepare_data.py:28:6 - error: Import "nlp_architect.pipelines.spacy_np_annotator" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/IntelLabs_nlp-architect/3f63387cff88f0074f1946bbbd1163fbfe97073e/a/solutions/set_expansion/prepare_data.py:29:6 - error: Import "nlp_architect.utils.text" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/IntelLabs_nlp-architect/3f63387cff88f0074f1946bbbd1163fbfe97073e/a/solutions/set_expansion/prepare_data.py:30:6 - error: Import "nlp_architect.utils.io" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/IntelLabs_nlp-architect/3f63387cff88f0074f1946bbbd1163fbfe97073e/a/solutions/set_expansion/prepare_data.py:32:6 - error: Import "tqdm" could not be resolved (reportMissingImports)
5 errors, 0 warnings, 0 infos 
Completed in 1.418sec

time cost(in seconds): 1.547631025314331
