No configuration file found.
No pyproject.toml file found.
stubPath /mnt/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/huggingface_transformers/1d8511f8f2c926c72146e87029d5b0acb48bd06e/typings is not a valid directory.
Assuming Python platform Linux
Searching for source files
Found 1 source file
/home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/huggingface_transformers/1d8511f8f2c926c72146e87029d5b0acb48bd06e/a/run_classifier_pytorch.py
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/huggingface_transformers/1d8511f8f2c926c72146e87029d5b0acb48bd06e/a/run_classifier_pytorch.py:27:8 - error: Import "torch" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/huggingface_transformers/1d8511f8f2c926c72146e87029d5b0acb48bd06e/a/run_classifier_pytorch.py:28:6 - error: Import "torch.utils.data" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/huggingface_transformers/1d8511f8f2c926c72146e87029d5b0acb48bd06e/a/run_classifier_pytorch.py:29:6 - error: Import "torch.utils.data.distributed" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/huggingface_transformers/1d8511f8f2c926c72146e87029d5b0acb48bd06e/a/run_classifier_pytorch.py:31:8 - error: Import "tokenization_pytorch" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/huggingface_transformers/1d8511f8f2c926c72146e87029d5b0acb48bd06e/a/run_classifier_pytorch.py:32:6 - error: Import "modeling_pytorch" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/huggingface_transformers/1d8511f8f2c926c72146e87029d5b0acb48bd06e/a/run_classifier_pytorch.py:33:6 - error: Import "optimization_pytorch" could not be resolved (reportMissingImports)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/huggingface_transformers/1d8511f8f2c926c72146e87029d5b0acb48bd06e/a/run_classifier_pytorch.py:400:22 - error: "f" is not defined (reportUndefinedVariable)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/huggingface_transformers/1d8511f8f2c926c72146e87029d5b0acb48bd06e/a/run_classifier_pytorch.py:401:23 - error: "f" is not defined (reportUndefinedVariable)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/huggingface_transformers/1d8511f8f2c926c72146e87029d5b0acb48bd06e/a/run_classifier_pytorch.py:402:24 - error: "f" is not defined (reportUndefinedVariable)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/huggingface_transformers/1d8511f8f2c926c72146e87029d5b0acb48bd06e/a/run_classifier_pytorch.py:403:22 - error: "f" is not defined (reportUndefinedVariable)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/huggingface_transformers/1d8511f8f2c926c72146e87029d5b0acb48bd06e/a/run_classifier_pytorch.py:498:48 - error: Argument of type "Unknown | None" cannot be assigned to parameter "__obj" of type "Sized" in function "len"
    Type "Unknown | None" cannot be assigned to type "Sized"
      "__len__" is not present (reportGeneralTypeIssues)
  /home/apr/data/2020-11-API-misuse/Repair_API_Misuse/api-misuse-repair/2_parse_dl_repos/repo_download_v2/misuse_repos/huggingface_transformers/1d8511f8f2c926c72146e87029d5b0acb48bd06e/a/run_classifier_pytorch.py:571:27 - error: "loss" is possibly unbound (reportUnboundVariable)
12 errors, 0 warnings, 0 infos 
Completed in 1.804sec

time cost(in seconds): 1.9913825988769531
